name: Scrape Sehir Hatlari

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes

permissions:
  contents: write   # allow the workflow to push changes

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        id: run
        run: |
          python scraper.py > run.log
          echo "result=$(tail -n1 run.log)" >> $GITHUB_OUTPUT

      - name: Commit changes (if any)
        if: steps.run.outputs.result == 'CHANGED'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/cancellations.txt
          git commit -m "Update cancellations [skip ci]"
          git push
